### PR TITLE
Control script to start and stop deployment and reset emergency services.

### LINKED ISSUE #143: log overall system start and stop
To allow us to judge how long the system runs for, please can someone add some logging to the AAF system on overall start up and shut down? For G4S this is done in the routine as follows:

``` python
        #this is in the init method:
        self._logging_msg_store = MessageStoreProxy(collection='task_events') 

        te = TaskEvent(task=None, event=TaskEvent.ROUTINE_STARTED, time=rospy.get_rostime(), description='Routine started')
        self._logging_msg_store.insert(te)
        rospy.on_shutdown(self._log_end)


    def _log_end(self):
        te = TaskEvent(task=None, event=TaskEvent.ROUTINE_STOPPED, time=rospy.get_rostime(), description='Routine stopped')
        self._logging_msg_store.insert(te)

```

### PR DESCRIPTION
**Pull request by cdondrup**
Closes #143, #177 

@Jailander please check if I forgot to reset any emergency services.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
This looks good to me and shall be merged, but @Jailander should still check the calls.

**Comment by Jailander** [comment]
`/safety_stop`, `/reset_safety_stop` and `/go_to_safety_point` are not included here

**Comment by Jailander** [comment]
sorry just saw this issue

**Comment by cdondrup** [comment]
OK, let's talk about that tomorrow.

**Pull request merged**
