### PR TITLE
Infoterminal waypoint proposer.

### PR DESCRIPTION
**Pull request by gestom**
To be tested.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
these network issues drive me nuts...

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
now we have a real problem:

```
[  5%] Building CXX object monitored_vcs/info_terminal/infremen/CMakeFiles/infremen.dir/src/infremen.cpp.o
/var/lib/jenkins/workspace/pr-indigo-aaf_deployment/monitored_vcs/info_terminal/infremen/src/infremen.cpp:22:30: fatal error: info_task/Clicks.h: No such file or directory
 #include <info_task/Clicks.h>
                              ^
```

**Comment by cdondrup** [comment]
`info_task` is missing in the CMakeLists.txt and package.xml.

**Comment by marc-hanheide** [comment]
Hooray!

**Pull request merged**
