### PR TITLE
Starting the walking_group_gui server also for bellbot under different name.

### PR DESCRIPTION
**Pull request by cdondrup**
Needs https://github.com/strands-project/strands_hri/pull/119 merged.

### CODE REVIEW

**Comment by cdondrup** [comment]
Doesn't need above PR merged and there will be code added to this. Don't merge, yet.

**Comment by cdondrup** [comment]
@marc-hanheide 

The arrow gui server now works as discussed:
- Publishes the direction the robot takes, i.e. left, right, straight, stop, on `~directions`. In the bellbot case: `bellbot_guiding_interface/directions`
- Needs to be started since it is an action server with a `aaf_walking_group/EmptyAction`. This is not really nice in your case but I don't want to change too much working code the weekend before deployment.

**Comment by marc-hanheide** [comment]
This introduces a dependency on strands_hri on the aaf_deploymenf repo... Causing a circular dependency?

**Comment by cdondrup** [comment]
Kind of... since this will never be released I don't think it matters much but it is not nice. As I said in the other PR, in hindsight, bellbot might have better been put in here.

As a solution, I could change the node to publish all the time but display the webpages only when the server is started. That wouldn't entail any changes in the walking group. Then this just publishes a string all the time and you have to take care of when to ignore it.

**Comment by cdondrup** [comment]
OK, the last one was a cheap fix. It now always publishes on the topic. Therefore this doesn't create a new dependency. The indicators won't do anything now, only if the action server is started. Will think of a solution for that.

Just listen to `bellbot_guiding_interface/directions` for left, right, or straight. Only publishes when it changes but on a latched topic.

**Comment by cdondrup** [comment]
I'll remake this into using dynamic reconfigure instead of being an action server:
- turn on/off indicators
- turn on/off webpage
- no action server = no more explicit starting of component

**Comment by cdondrup** [comment]
The walking_gui_server is now just a simple script running which could be run all the time. The parameters:
- `web_page`: show the web pages with arrows
- `indicators`: use the indicators
- `move_head`: move the head to indicate direction
  can now be set on start-up or dynamically reconfigured. In theory the script could run the whole time in background and publish the direction and use the indicators and head. When the walking group is running, I reconfigure it when I need the web page shown and turn it off when not.

**Comment by cdondrup** [comment]
Tested on robot. @marc-hanheide please merge if that is closer to what you wanted.

**Comment by marc-hanheide** [comment]
Can't be merged automatically...

**Comment by cdondrup** [comment]
Weird... there were no conflicts when merging indigo-devel.

**Pull request merged**
