### PR TITLE
Moving music player for walking group here

### PR DESCRIPTION
**Pull request by cdondrup**
Needs https://github.com/strands-project/strands_deployment/pull/81 merged

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I wondered: Is this a generic music player? Then I'd prefer it in strands_ui, @nilsbore ?

**Comment by marc-hanheide** [comment]
So, it would be similar to mary_tts...

**Comment by marc-hanheide** [comment]
Having had a look again, I want to decline this PR and refer it over to strands_ui if possible. Of course that would requiring some renaming as well, but this is too generic for this repo. Others want to play music, too ;-)
OK, @cdondrup @nilsbore ?

**Comment by cdondrup** [comment]
I'm on the case. The other PRs should remain open until the renaming is done.

**Comment by nilsbore** [comment]
@cdondrup Are you already on it or do you want me to do this?

**Comment by cdondrup** [comment]
Not yet, but since all the other PRs are mine I will do the renaming in there as well. Don't worry.

**Comment by nilsbore** [comment]
@cdondrup Cool.

**Pull request closed without merging**
