### PR TITLE
[info_terminal] Simple replacement for approach person. 

### LINKED ISSUE #78: [info-terminal] new task action server replacing approach_person_of_interest
- [x] the current [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) should be refactored to be based on [AbstractTaskServer](https://github.com/strands-project/strands_executive/blob/hydro-release/strands_executive_msgs/src/strands_executive_msgs/abstract_task_server.py), so that a factory service for tasks (`..._create`) is available. 
- [x]  [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) needs to be modified so it doesn't use a `Pose` to turn towards, as we don't have waving detection. Instead, it should just run at the waypoint, make the head and PTU turn towards the screen, and enable [strands_gazing](https://github.com/strands-project/strands_hri/tree/hydro-devel/strands_gazing) rather than approaching a person

### PR DESCRIPTION
**Pull request by cdondrup**
Closes #78 

Inherits from AbstractTaskServer for easy task creation.

**Functionality:**

When active,
- turn the PTU and head back, and activates looking at upper bodies.
- listen to button clicks and save the page numbers and times.

When preempted, publish a custom massage on `/info_terminal/task_outcome`, containing an array of ROS times when the click occurred and array of page numbers that were selected. The indexes of both arrays correspond to each other.

**Usage:**
Creating a task: Call the `/info_task_server_create` service. This has an optional string argument to pass a yaml file location. This could be used to fill the fields with default values. If no yaml file is give, the task will have the correct action name and a default `max_duration` of 10 minutes which can of course be overridden. Please set `start_node_id` and `end_node_id`, `start_before` and `end_before`. Notice, the window created by `start_before` and `end_before` has to be larger than `max_duration`.

This task can then be sent to the scheduler.

**Main differences to approach_person_of_interest**
- No approaching because we don't have a wave detector
- Clicking a button will not prolong the time the robot stays at the waypoint. This was done by not allowing to preempt the task while buttons were pressed. This is creating unpredictable behaviour and prevents the scheduler from doing its job. As discussed with @gestom, this will be solved by sending a new task at the same location if the last interaction was successful.

Needs proper testing with the interface and on the robot. The port for the used webserver might have to be changed.

### CODE REVIEW

**Comment by cdondrup** [comment]
The custom message with the times and pages could also be stored in the message store directly, see #77

**Comment by marc-hanheide** [comment]
Yes, can @gestom please check this first please and then maybe @yianni or @nilsbore can test on their robots?

**Comment by cdondrup** [comment]
Just talked to @gestom, works fine on Linda.

**Comment by marc-hanheide** [comment]
:+1: with this being just adding a new package I'll accept it.

**Pull request merged**
