### PR TITLE
new info terminal as suggested by Matei

### PR DESCRIPTION
**Pull request by marc-hanheide**
This is the work to address #348 This is work in progress, not to be merged until further notice

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@capamat-aaf it looks like this:

image

**Comment by marc-hanheide** [comment]
OK, the version of 876cd4ca6d64b16bcdcc535527a3a1f11b6f24ab looks like shown in this video:

https://www.youtube.com/watch?v=-9zRxs-UJa8

This should address most new aspects. In particular implemented is:
- [x] React to touch events (not need to release the button before page is loaded
- [x] immediate touch feedback (button changes, and "loading" pop-up is displayed)
- [x] padding of buttons as requested
- [x] re-layouted content to match the new design with the static menu bar
- [x] some internal restructuring for better management

Still to be done:
- [ ] some minor design changes (line spacing etc)
- [ ] better logging of interactions (position of clicks etc.)
- [ ] whatever @capamat-aaf might identify ;-)
- [ ] testing with other browsers than Chrome
- [ ] start screen ("Screen saver")

I have deployed this version to the AAF Laptop for testing locally. @capamat-aaf if you direct your browser to http://192.168.200.20:8080/info (in the STRANDS network or on the laptop) to get started.

**Comment by capamat-aaf** [comment]
Thank you Marc, it works great!
So I identified [:-)] following things:
• Menu is in English, idk if this is the same that gets uploaded to Henry, but there we need German
• at News, when there aren't any, it says "no News at the moment", also in English
• "Photoalbum", "no photos at the moment", and "Previous+Next photo" also to be translated
• I watch the video, it seems a bit small, but I guess it's adapted to Henry's screen size. 
I couldn't hear the audio, maybe it's because of the laptop, does it wrk for you?
• After the video it forwards to the old "start screen". Now the question, if it should forward to something else or just loop the video? And at the old start screen there are is no "Loading" screen when clicking through.
• About the menu items:
    - technically we are missing Clock and Bellbot, but then we would have eight. Would it be possible to  consolidate the Menu buttons and then have an additional screen for choosing which menu people want to see? This could then be the default screen when roaming the café area. If it is possible...
- Clock is a bit of a mystery. I'm a bit in denial, if people actually click on it, if it's only a separate button. Regardless, 7 items would've have still been possible, iirc, so if the consolidation of the menu works, then that should be fine, I hope. 

PS: tested it on the Firefox browser in the small laptop. The content is upper-left-corner oriented, but otherwise

**Comment by marc-hanheide** [comment]
Thanks @capamat-aaf 

A few notes:
- The language is just a flag, I restarted it in German
- That some news are not available is due to the limited setup on that laptop at the moment. I actually implemented proper error handling and this shows it's working. Before, you got an ugly error message, not it tell just if it can't receive news (or weather). This can happen if the internet connection drops for some time, so it's important we handle it properly. Same applied to the photos. On the laptop, none are available, so you see that none are available, and not an ugly backtrace of failure.
- The old main menu will disappear (and so will the redirect at the end of the video), As we discussed, there will be a new home screen, showing the time, and instructing people to touch the screen to reveal more information (the "screensaver")
- Do we want bellbot to be triggered from this? I didn't anticipate that...

**Comment by capamat-aaf** [comment]
What could be the alternative implementation? We don't have an evaluation planned specifically around it (only, just as with the others, if and how many times it's being used), but a the same time it shouldn't be dropped, so I don't know how else people could call it.

**Comment by marc-hanheide** [comment]
Normally it had been called from the admin interface or scheduled.

**Comment by capamat-aaf** [comment]
I know that barely anyone ever used the function, in all of the deployments.
I wonder if in that case adding it to the menu will make it more accessible for people to use it.
I'm not sure what the best course of action is; if it fits, would it be possible to have it there?
If not, then it can stay the way it was.

**Comment by marc-hanheide** [comment]
I really don't know... I fear people might accidently triggering this without fully understanding the consequences. Enabling everybody to do this is certainly a shift of requirements.

**Comment by capamat-aaf** [comment]
You're right that might happen.
I just thought of a possible evaluation idea of this task; since we are a teaching care hospital, we have medicine students coming for courses. 
Perhaps we can schedule Henry to be available for the bellbot and see whether they use it or not and then evaluate this.
Am I right though; was the bellbot scheduled to run from X o'clock to Y o'clock?

**Comment by marc-hanheide** [comment]
Yes, it was put in the schedule for a fixed period to pick people up at a location. That's how it would work.

**Comment by marc-hanheide** [comment]
@gestom @Jailander: I have now changed the feedback topic to be latched and to be a string. This string indicated the sub-page that has been looked at (the url-suffix). This can then be used to build information specific models.

**Comment by marc-hanheide** [comment]
Quoting myself from the last commit message:

> - Clicks msg has changed and now contains the strings of all URL looked at during one task
> - The active_screen topic also now uses string
> - info_terminal_gui has changed to accept an URL-encoded /?page=news etc to indicate the default page
> - info_terminal_gui has a new home screen using the default page to prominently allow users to go there
> - better layout and localisation
> - info_task_server creates individual tasks for all the possible default pages
> - still missing: bellbot

In other words: everything required for @gestom to suggest the right default task is in place and also @gestom gets the feedback to train models. The key topics to check for in this new implementation are `/info_terminal/active_screen` which always publishes the URL suffix (e.g. `news` or `weather`) in the moment the page is loaded. In `/info_terminal/task_outcome` topic, a summary of all pages visited ("number of clicks") is presented (as before, but now with strings instead of Int32 as discussed).
The new tasks that can be triggered have the following name scheme: `/info_task_server/$URL`, so e.g. `/info_task_server/news` or `/info_task_server/weather` to indicate a task with the corresponding default page suggested to users.

Here's an example of the new start screen (here for a task `/info_task_server/news`)
image

Users are given extra information and they can click anywhere on the screen _above_ the menu to go to the news section in this case. A click on the menu buttons at the button still leads them to the other pieces of information.

For @capamat-aaf to take note, and for @gestom and @Jailander to try out.

**Comment by marc-hanheide** [comment]
updated video: https://www.youtube.com/watch?v=VlKgH8pZGeI

**Pull request merged**
