### PR TITLE
[aaf_bringup] Added the reset bumper duration to navigation launch

### PR DESCRIPTION
**Pull request by nilsbore**
Requires https://github.com/strands-project/strands_navigation/pull/246#issuecomment-101670533 .

### CODE REVIEW

**Comment by Jailander** [comment]
its conflicting with PR #218

**Comment by cdondrup** [comment]
Merge this and I resolve the conflicts.

**Comment by Jailander** [comment]
I have no power here :P

**Comment by Jailander** [comment]
I tested it and it works in Linda so merge if you want

**Pull request merged**
