### PR TITLE
Improved control ui

### PR DESCRIPTION
**Pull request by marc-hanheide**
this also removes one wrong file I found, but mostly this is about finalising the control UI, in particular addresses most features in #199

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Oh, this is currently already running on https://lcas.lincoln.ac.uk/werner/

**Comment by cdondrup** [comment]
Except for the on demand tasks, this seems to work, do you want to change that first or should I merge?

**Comment by marc-hanheide** [comment]
did you test the tasks again? I fixed them... maybe...

**Comment by cdondrup** [comment]
The robot is currently on its charging station since none of the personal is around any more. You are welcome to test, see calendar for currently active task.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
the `charging_task` is not interruptible, so I guess it is stuck now ;-) Seriously, I have a load of other things to do, so I leave this to tomorrow. I did some test while you were at lunch and it behaved reasonably, but it as not a full-blown test with other tasks around, so let's give it another go tomorrow.

**Comment by cdondrup** [comment]
Sounds good. To get rid of the task, just kill the scheduler launch file and remove it from the calendar ;)

**Pull request merged**
