### PR TITLE
Added video to info terminal

### PR DESCRIPTION
**Pull request by marc-hanheide**
This shows the instruction video on the info terminal main screen. This needs testing in terms of memory and CPU usage. @cdondrup let's do this once walking group is done with?

### CODE REVIEW

**Comment by cdondrup** [comment]
Will do

**Comment by cdondrup** [comment]
Could also add the video into the media server and then use something like this: https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_walking_group/www/video.html

Should also loop the video.

**Comment by marc-hanheide** [comment]
@TobKoer new main page:
image

new video page:
image

**Comment by TobKoer** [comment]
@marc-hanheide  Yes! :-)

**Comment by denisehe** [comment]
cool

**Pull request merged**
