### PR TITLE
Walking group map interface

### PR DESCRIPTION
**Pull request by cdondrup**
This PR introduces the most important changes from #288 

**New features:**
- The Therapist interface has been redesigned to make the back buttons more obvious and to show that the waypoint selection is now done via a map
  
  guide_interface
- Waypoints can now be reached by either just pressing the "Weiter" button or by selecting them from the map by pressing one of the little "Rast" buttons. The robot will then figure out where in the tour it is and which waypoints to traverse in between using _Magic_, i.e. a lot of topological rout planning and reasoning I don't expect any one to understand or even wanting to try to. The button in the bottom right is the back button.
  
  map
- When a resting area is reached the therapist will still be asked if they really want to rest and if they confirm this, a very abstract map of the resting area is shown on which each button represents a chair and by pressing it the robot will move there for the duration of the rest. Below the "map" for the "Ambulanz" and the view in rviz showing how this looks for the robot.
  
  ambulanz
  
  ambulanz_riz
  
  All these nodes use localise by topic, so only if the correct node name is published on `/aaf_walking_group/resting_node` and the robot reached the correct position, it will be localised as being there. This should prevent any nastiness with the MDP planning. Needs https://github.com/strands-project/strands_navigation/pull/299 merged.
  The correct nodes are identified using tags, i.e. WayPoint92 has the tag `ambulanz0` which is encoded in the map for the therapists and will be used to find this node. The node name is therefore looked up and essentially irrelevant. Only the tag has to be named correctly and exist.
- The deployment control node now also offers the service `/deployment_control/show_maintenance` and `/deployment_control/hide_maintenance` which when triggered show a generic mantenance and out of order message for feedback to the therapists or anyone in general. This uses @marc-hanheide 's dialogue boxes. The service will be triggered by the person observing the walking group remotely from Lincoln. Sadly, there is no way of relying on the robot to display that it broke. Depending on what broke this might not be possible at all but at least this is an option of feedback to the therapists.
- Updated the recording white list with all the new resting nodes. The actual topological map needs a bit of love from @Jailander to be able to be used on the robot and will be tested on Monday.

PR also includes some bug fixes.

### CODE REVIEW

**Comment by cdondrup** [comment]
Also removed the video button from the entertainment interface. This might be reintroduced if I (or anyone else) is able to make it work reliably without eating all the RAM.

**Comment by marc-hanheide** [comment]
This deserves the award for best documented pull request ;-)

Shall we test this on Monday before merging? If so, it should be merging upstream before we do the test.

**Comment by cdondrup** [comment]
Sounds good! And thanks :)

**Comment by cdondrup** [comment]
This last commit adds a [node](https://github.com/cdondrup/aaf_deployment/blob/walking_group_map_interface/aaf_walking_group/scripts/walking_group_recovery_feedback.py) that subscribes to `/move_base/state` and `/move_base/DWLocalPlanner/local_plan` and compares their timestamps. If they are more than 5 seconds apart, the DWA planner cannot produce a path and is stuck. This is only valid if there is an active move_base goal. 

If the robot is stuck, a dialogue is shown to inform the therapists about that. If the robot frees itself or the move_base goal is cancelled to trigger the human help recovery or the back tracking, the dialogue is also removed. Hence it should not interfere with any of the more high level recoveries.

**Comment by marc-hanheide** [comment]
Regarding 3d20cb0868eccef91e949217b55ab589b6320027 this can have some unwanted side effects, right? Assume we decided to display a modal dialog to the user (e.g. telling them we are sorting things out) and then DWA eventually finds a path again, it will remove whatever dialog is currently displayed, and/or will overwrite it with its own. We don't have "layers" or "priorities" of modal dialogs. Is this a problem?

**Comment by cdondrup** [comment]
I could have a service that disables this node. That would then be coupled with the `/deployment_control/{show|hide}_maintenance` service. Also, this will only be running during the walking group.

This is the only way I could think of having an automatic feedback to the therapist to show that the robot is stuck and will try to recover. Since it might take a while before the robot does something again or gives any feedback, I thought that would be nice.

**Comment by marc-hanheide** [comment]
Makes all total sense. Just wanted to make you aware of the potential problems. As long as the walking group "supervisor" (ie us) is aware, I don't think you need to do anything. But we need to check how often this is triggered as it has the potential to also be annoying...

**Comment by cdondrup** [comment]
Here e8f5264 my suggested solution. And yes, I love lambda functions ;)

Being aware of this is also recommended, yes. I will observe how often this appears but since there has to be a timeout of more than 5 seconds, I don't think that will happen too often.

**Comment by denisehe** [comment]
Hello!

WOOOW really cool! 
I especially love the new map with the way point overview...although this (I guess) showes just very little of the whole effort you took!

I am in the office now. When should we run the tests?

Cheers Denise

**Comment by cdondrup** [comment]
Thanks! We currently have troubles with the robot and it ran out of charge over the weekend. So I think around lunch time, the earliest :(

**Comment by denisehe** [comment]
ok fine fore me! I will be in the office longer today.

i just rememberd: what interface is shown during the drive? 
is there also the possibility to adjust the volume? (i dont dare to aks, but i have to)

**Comment by cdondrup** [comment]
We could do that but that would mean that you have to catch the robot while it is driving. Maybe @marc-hanheide can create a webpage like the one that is used in the bellbot (while it is driving) with the volume buttons on it.

**Comment by denisehe** [comment]
Yes please! 
That does not matter, it drives in a speed, the therapists can easily can cath up with it.
I just remembered that this was also a feedback from the therapists, that it would be easyer if they could adjust the volume without using the card.

**Comment by cdondrup** [comment]
You can now in the music interface during the entertainment phase

song

Not sure if that is enough.

**Comment by cdondrup** [comment]
And I actually I thought that was what they wanted...

**Comment by denisehe** [comment]
ok but thats during the rests, right?

**Comment by cdondrup** [comment]
Yes, but what ever volume you choose would also be used while it driving...

**Comment by cdondrup** [comment]
OK, here is the thing: The webpage that the bellbot uses is done by @marc-hanheide  in webpy and I have no idea how that works. If I just add the buttons to all of the webpages I am currently using they will load considerably slower and might not be quick enough any more to show anything during the drive. Hence, I would have to leave this to @marc-hanheide to implement. For now, we should test it as it is.

**Comment by denisehe** [comment]
hmmmm ok.
I for my point of few would be satisfied with that...but i think to follow the wish of the therapists would be good, cause 1 of all it enhances their feeling of easy (!) controle....and it also showes that we took their feedback into account also in that matter.

would that be possible?

**Comment by cdondrup** [comment]
As I said, I spent my weekend on doing what you currently see and I don't have the time to learn webpy as well. Sorry but that is for @marc-hanheide 

I would have attempted that but I understood that the therapists wanted to control the volume during the resting phases without using the card (which you can now). At least that is what I got from the discussion we had with them during the meeting at the pre-deployment. If you got different feedback, I wasn't made aware of that.

**Comment by denisehe** [comment]
yes I read that before, your second time mentioning that marc is responsible for that did not update in time!

the feedback, as I understood, was to be able to conrol the volume without the  card, at all times.

**Comment by denisehe** [comment]
yes, i know that u put much efford into the walking group!!! 
but as this issue came up just now, i could feed in my perspecive also just now.

Sorry again!

**Comment by cdondrup** [comment]
I'm sorry but my comment https://github.com/strands-project/aaf_deployment/issues/288#issuecomment-188360371 with all the things to implement is almost a month old. So I feel that there was more than enough time for input.

**Comment by denisehe** [comment]
hi again, well I actually was on vacation during that time and as always i cannot log onto the system from abroad with my work laptop!

When I red it after my return (last week) i assuemd that you meant volume adjustment in terms I understood the request of the therapists - and considered it okay.

I mean I really do feel akward if these things come up like "last minute", i appreciate you work and efford (as always by the way), I also am aware that you are super busy!!
but on some points its also difficult for us when implemented tasks can be tested so close to the actual trial/or during the trial - cause this is the situation where we can really grasp/see how it actually looks like or how things work etc. and thats also the moment when misunderstandings like these become clear...

**Comment by cdondrup** [comment]
The page with the arrows now has volume buttons as well.

arrow

**Comment by marc-hanheide** [comment]
I suppose we still don't merge this, or do we?

**Comment by cdondrup** [comment]
After the test tomorrow.

**Comment by marc-hanheide** [comment]
:+1:

**Comment by denisehe** [comment]
perfect!
many thanks!
:+1:

**Comment by cdondrup** [comment]
Tested. Discovered a few extra things to add or change. Will do in a separate PR.

**Pull request merged**
