### PR TITLE
New facebook news

### PR DESCRIPTION
**Pull request by marc-hanheide**
addressing requirements in #287 

Now looks like this (with the left taken directly from facebook):

image

from this Facebook feed:
image

Images are not easily possible, due to permission management on facebook and also they would be too small in our GUI.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@TobKoer @denisehe please comment.

**Comment by marc-hanheide** [comment]
I should mention, this is now fully updated, so the wordpress blog is "not" used anymore. We could alternatively take the first item form the blog and then put two facebook items below or similar.

**Comment by Jailander** [comment]
shouldn't we have a werner FB profile or some fake one so its not your account @marc-hanheide ?

**Comment by marc-hanheide** [comment]
@Jailander where is it my account? Did you see anything you were not supposed to see?

**Comment by Jailander** [comment]
your profile pic is next to the write a comment section

**Comment by marc-hanheide** [comment]
Oh, you meant in that screen shot... No, that _is_ my facebook stream obviously. The news are pull from that stream, but via the Facebook API. I created a Facebook App that does that. I'm the registered developer at Facebook for this, but that's all. It doesn't access it via my account.

**Comment by Jailander** [comment]
Ah ok, sorry I thought it was like the twitter app on strands on which you have to register though an account but then again that is just for publishing

**Comment by TobKoer** [comment]
@marc-hanheide 
Cheers.

It looks good, but I think text is too small for most residents to clearly read. Maybe less news and bigger fonts?!
Will have to test on the actual robot screen as soon as Henry is 'info-terminating' again.

**Pull request merged**
