### PR TITLE
adding the wifiscanner

### PR DESCRIPTION
**Pull request by marc-hanheide**
@nilsbore to check this is the right place, please.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
release is on the way... should be available soon.

**Comment by marc-hanheide** [comment]
it should be available now, @nilsbore if you could log `/wifiscanner` as well, that would be good.

**Comment by nilsbore** [comment]
Added it.

**Comment by marc-hanheide** [comment]
@nilsbore @cdondrup, please make sure `ros-indigo-wifiscanner` is installed on the robot's main PC.

Thanks

**Pull request merged**
