### PR TITLE
Y4 deployment

### PR DESCRIPTION
**Pull request by Jailander**
Adding new scheduler to routine launch file and start script

### CODE REVIEW

**Comment by Jailander** [comment]
@marc-hanheide do you know why this is failing?

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
seems Trump has disabled the internet... no idea why it failed, it was not able to connect to some servers.

**Comment by Jailander** [comment]
HAHA, it must be all the data being transferred to Russia

**Comment by marc-hanheide** [comment]
worked now.

**Comment by marc-hanheide** [comment]
do you want to merge now or better wait for all the other small changes?

**Comment by Jailander** [comment]
No keep it open please still need to change the tmux and a few minor things

**Comment by marc-hanheide** [comment]
Merge now?

**Comment by Jailander** [comment]
yes please

**Pull request merged**
