### PR TITLE
updated bellbot map

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by Jailander** [comment]
@marc-hanheide  do you know why this is failing?

**Comment by marc-hanheide** [comment]
Network issues... Try later again

**Comment by Jailander** [comment]
Ah ok just thought there was something worng as it is the second commit that failed here

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
there was indeed a bug in the network multiplexer on lcas.lincoln.ac.uk... Hopefully fixed.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
finally...

**Comment by marc-hanheide** [comment]
finally...

**Comment by Jailander** [comment]
merge?

**Pull request merged**
