### PR TITLE
switching topological maps before and after walking_group

### PR DESCRIPTION
**Pull request by Jailander**
@cdondrup can you revise and comment please! :)

### CODE REVIEW

**Comment by cdondrup** [comment]
If it works for you, then it should be alright. However, we want to make sure that it really loads the map, currently it just prints an error and then starts it anyway. I'd suggest something like this:

``` python
...
self.switch_map(topological_map_name=rospy.get_param('/walking_group_topological_map','aaf_WG_y4'))
...

def switch_map(self, topological_map_name):
    while not rospy.is_shutdown() and not self.server.is_preempt_requested():
        try:
            rospy.wait_for_service('/topological_map_manager/switch_topological_map', timeout=10)
            cont = rospy.ServiceProxy('/topological_map_manager/switch_topological_map', strands_navigation_msgs.srv.GetTopologicalMap)
            resp1 = cont(topological_map_name)
            if resp1.map:
                rospy.loginfo("Switched Topological maps to: %s" %topological_map_name)
                return
            else:
                rospy.logwarn("Couldn't Switch Topological maps to: %s, retrying." %topological_map_name)
        except rospy.ServiceException, e:
            rospy.logerr("Service call failed, retrying: %s"%e)
        rospy.sleep(1.)
```

_Not tested_

**Comment by Jailander** [comment]
Ok good idea, haven't tested it yet, will do tomorrow, thank you!

**Comment by cdondrup** [comment]
Looks good to me. I'll trust in your ability to test that ;)

**Comment by marc-hanheide** [comment]
Has this been tried?

**Comment by Jailander** [comment]
Tested can be merged

**Pull request merged**
