### PR TITLE
Task start delay now dynamically configurable.

### PR DESCRIPTION
**Pull request by gestom**
The infoterminal tasks start at Hour:Minute:taskStartDelay.
This allows to give more time to re-schedule the infoterminal tasks in cases when the battery is low or when there was an interaction with the infoterminal during the last 3 minutes

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@cdondrup did we run this today already?

**Comment by cdondrup** [comment]
No, I can try it together with the PR for the scheduler.

**Comment by cdondrup** [comment]
Sadly, this doesn't seem to work @gestom 

```
[ INFO] [1431447300.945227722]: Task 2 should be changed to charging.
[ INFO] [1431447306.528070821]: Task 2 cancelled, replanning.
[ INFO] [1431447306.532739270]: Task 6 created ChargingPoint for timeslot 207 on 2015-05-12_17:15:00. at 
[ INFO] [1431447306.540018898]: Task 7 created WayPoint26 for timeslot 211 on 2015-05-12_17:35:00. at
```

ROS time: `1431447300 = 12/05/2015, 17:15:00 GMT+1:00 DST`

I set `taskStartDelay` to 59 so this should have changed it a minute before the task starts?! but it just did at exactly the time when the task started.

**Comment by cdondrup** [comment]
OK, I misunderstood how this works. Due to the schedulers new feature of trying to be at the desired waypoint in time, this has to be changed because the robot now starts navigation before the task starts. Therefore it will drive to the previous location event though the task would be cancelled.

**Comment by cdondrup** [comment]
With the new commit, the time before the end of the current task at which the next task will be changed to be at the charging station is now configurable. We should put a test for this on tomorrows agenda. Works for me in simulation but charging doesn't work properly which makes it hard to test.

**Comment by gestom** [comment]
I will test on Linda.

**Comment by cdondrup** [comment]
Merging to make minor changes on robot and commit afterwards.

**Pull request merged**
