### PR TITLE
Moving walking group main package to here

### PR DESCRIPTION
**Pull request by cdondrup**
Needs https://github.com/strands-project/strands_deployment/pull/79 merged.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
`KeyError: 'aaf_music_player'`

Where would that one be? Or is this a reference to the coming https://github.com/strands-project/strands_ui/pull/62 ?

**Comment by cdondrup** [comment]
Sorry, this is still in strands_deployment. I will move that over when I'm back in the office. Then it will work.

**Comment by marc-hanheide** [comment]
Rather than moving that, can we try to base it on `pygame_managed_player`, or base the aaf_player on it, I mean?

**Comment by cdondrup** [comment]
@marc-hanheide I don't quite get your last comment. The reason this depends on `aaf_music_player` is because it calls a few of its services so this package, the `aaf_walking_group`, does not have anything to do with the pygame thing directly. So I guess with https://github.com/strands-project/strands_deployment/pull/80 this is obsolete and it can be moved?!

**Comment by marc-hanheide** [comment]
yes, forget about my comment. A mix of outdated information and wrong auto-correction...

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
jenkins having network issues again...

**Comment by marc-hanheide** [comment]
a, no... the problem is that `music_player` is not resolved yet, obviously. Let's wait for strands_ui to be re-released.

**Comment by marc-hanheide** [comment]
ok, music_player released

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
sorry, still not... missing `walking_group_recovery`

**Comment by cdondrup** [comment]
strands_recovery_behaviours needs to be re-released as well.

**Comment by marc-hanheide** [comment]
will you do that?

**Comment by cdondrup** [comment]
I'll fix it. Just had to equalise the version numbers and am waiting for the devel build to finish ;)

**Comment by cdondrup** [comment]
retest this please

**Comment by cdondrup** [comment]
Finally

**Pull request merged**
