### PR TITLE
Data transfer task

### PR DESCRIPTION
**Pull request by marc-hanheide**
a first go at having a task to transfer data to replication node

### CODE REVIEW

**Comment by marc-hanheide** [comment]
this should be added to the logging launch file (the one that runs continuously)

**Comment by hawesie** [comment]
Are you using any other routine except the gcal one?

**Comment by hawesie** [comment]
Because if you're using a robot routing instance to do charging and docking (which maybe you should be?) you can just add this as a night task to that routine.

**Comment by marc-hanheide** [comment]
no, we are not using those... To be honest, I find these routines very cryptic. And the strict day/night pattern there was one of the biggest problems in our museum deployment, because we couldn't delay things for even half an hour easily. Put we do have another routine, namely the patrol/info-terminal one, that monitors battery levels and schedules charging if need be. Also, we schedule dedicated charging actions, and hence also data upload actions in the gcal. So, we effectively run two routines, but none of your :smirk:

**Pull request merged**
