### PR TITLE
adding bellbot launch file

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by cdondrup** [comment]
We can have a look at using axlaunch and the task server to launch this tomorrow.

**Comment by Jailander** [comment]
yes I just put it there so I don't forget ;)

**Comment by cdondrup** [comment]
This fails because the bellbot stuff in strands_hri is not released yet.

**Comment by cdondrup** [comment]
retest this please

**Comment by marc-hanheide** [comment]
retest this please

**Pull request merged**
